/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ProjetoGames.view;

import br.com.ProjetoGames.data.FuncionarioData;
import br.com.ProjetoGames.model.FuncionarioModel;
import br.com.ProjetoGames.model.UsuarioModel;
import br.com.ProjetoGames.view.Operacao.JFCadJogo;
import br.com.ProjetoGames.view.Operacao.JFLocacao;
import br.com.ProjetoGames.view.Operacao.JFPesquisarJogo;
import br.com.ProjetoGames.view.Operacao.JFVenda;
import java.awt.Font;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Pedro
 */
public class JFPrincipal extends javax.swing.JFrame {
    
    UsuarioModel obj;
    
    public JFPrincipal() {
        initComponents();
        setIcon();
        tempo();
        windowsClosing();
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
    }
    
    public JFPrincipal(UsuarioModel obj) {
        initComponents();
        this.obj = obj;
        jlInfo.setText("Login : "+obj.getNome()+" Tipo: "+obj.getTipoUsuarioModel().getDescricao());
        setIcon();
        tempo();
        windowsClosing();
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jlTime = new javax.swing.JLabel();
        jbRenovar = new javax.swing.JButton();
        jbRegistro = new javax.swing.JButton();
        jbLocacao = new javax.swing.JButton();
        jbVenda = new javax.swing.JButton();
        jbCadJogo = new javax.swing.JButton();
        jbCadUsuario = new javax.swing.JButton();
        jlInfo = new javax.swing.JLabel();
        jlFFxv = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmUsuario = new javax.swing.JMenuItem();
        jmJogo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmAlterarSenha = new javax.swing.JMenuItem();
        jmEditarDados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Garnet Games");
        setMaximumSize(new java.awt.Dimension(845, 760));
        setMinimumSize(new java.awt.Dimension(845, 760));
        setPreferredSize(new java.awt.Dimension(845, 760));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jdpPrincipal.add(jlTime);
        jlTime.setBounds(260, 30, 390, 70);

        jbRenovar.setBackground(new java.awt.Color(107, 164, 194));
        jbRenovar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbRenovar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Replace_50px.png"))); // NOI18N
        jbRenovar.setText("Renovar Locação");
        jbRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRenovarActionPerformed(evt);
            }
        });
        jdpPrincipal.add(jbRenovar);
        jbRenovar.setBounds(0, 160, 250, 50);

        jbRegistro.setBackground(new java.awt.Color(107, 164, 194));
        jbRegistro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Paste_40px.png"))); // NOI18N
        jbRegistro.setText("Registros Gerais\n");
        jbRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRegistroActionPerformed(evt);
            }
        });
        jdpPrincipal.add(jbRegistro);
        jbRegistro.setBounds(0, 400, 250, 50);

        jbLocacao.setBackground(new java.awt.Color(107, 164, 194));
        jbLocacao.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Procurement_48px.png"))); // NOI18N
        jbLocacao.setText("Realizar Locação");
        jbLocacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLocacaoActionPerformed(evt);
            }
        });
        jdpPrincipal.add(jbLocacao);
        jbLocacao.setBounds(0, 80, 250, 50);

        jbVenda.setBackground(new java.awt.Color(107, 164, 194));
        jbVenda.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Buy_48px.png"))); // NOI18N
        jbVenda.setText("Realizar Venda");
        jbVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVendaActionPerformed(evt);
            }
        });
        jdpPrincipal.add(jbVenda);
        jbVenda.setBounds(0, 320, 250, 50);

        jbCadJogo.setBackground(new java.awt.Color(107, 164, 194));
        jbCadJogo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCadJogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Overwatch_48px_1.png"))); // NOI18N
        jbCadJogo.setText("Cadastro Jogos");
        jbCadJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadJogoActionPerformed(evt);
            }
        });
        jdpPrincipal.add(jbCadJogo);
        jbCadJogo.setBounds(0, 240, 250, 50);

        jbCadUsuario.setBackground(new java.awt.Color(107, 164, 194));
        jbCadUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbCadUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Add_User_Male_48px.png"))); // NOI18N
        jbCadUsuario.setText("Cadastro Usuário\n");
        jbCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadUsuarioActionPerformed(evt);
            }
        });
        jdpPrincipal.add(jbCadUsuario);
        jbCadUsuario.setBounds(0, 0, 250, 50);

        jlInfo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlInfo.setText("Login: ");
        jdpPrincipal.add(jlInfo);
        jlInfo.setBounds(260, 0, 590, 30);

        jlFFxv.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlFFxv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/cxdkpvuxuaazxj8_8h6c.jpg"))); // NOI18N
        jdpPrincipal.add(jlFFxv);
        jlFFxv.setBounds(0, 0, 849, 1070);

        getContentPane().add(jdpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 760));

        jMenuBar1.setBackground(new java.awt.Color(131, 177, 203));

        jMenu1.setText("Pesquisar");

        jmUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        jmUsuario.setText("Usuário");
        jmUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jmUsuario);

        jmJogo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        jmJogo.setText("Jogo");
        jmJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmJogoActionPerformed(evt);
            }
        });
        jMenu1.add(jmJogo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Opções");

        jmAlterarSenha.setText("Alterar Senha");
        jmAlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlterarSenhaActionPerformed(evt);
            }
        });
        jMenu2.add(jmAlterarSenha);

        jmEditarDados.setText("Editar Dados");
        jmEditarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEditarDadosActionPerformed(evt);
            }
        });
        jMenu2.add(jmEditarDados);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadUsuarioActionPerformed
        new JFCadCliente(obj,1).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jbCadUsuarioActionPerformed

    private void jbCadJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadJogoActionPerformed
        new JFCadJogo(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jbCadJogoActionPerformed

    private void jbVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVendaActionPerformed
        new JFVenda(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jbVendaActionPerformed

    private void jbLocacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLocacaoActionPerformed
        new JFLocacao(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jbLocacaoActionPerformed

    private void jbRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbRegistroActionPerformed

    private void jbRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRenovarActionPerformed

    }//GEN-LAST:event_jbRenovarActionPerformed

    private void jmUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmUsuarioActionPerformed
        new JFPesquisarUsuario(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jmUsuarioActionPerformed

    private void jmAlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlterarSenhaActionPerformed
        new JFTrocarSenha(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jmAlterarSenhaActionPerformed

    private void jmJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmJogoActionPerformed
        new JFPesquisarJogo(obj).setVisible(true);
        dispose();
    }//GEN-LAST:event_jmJogoActionPerformed

    private void jmEditarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEditarDadosActionPerformed
        if (obj.getId() > 0) {
            try {
                if (obj.getTipoUsuarioModel().getNivel() <= 0) {
                    new JFCadCliente(obj, obj, 1).setVisible(true);
                } else {
                    if (obj.getTipoUsuarioModel().getNivel() > 0) {
                        FuncionarioData DAOF = new FuncionarioData();
                        FuncionarioModel objF = new FuncionarioModel();
                        objF = DAOF.pesquisarObj(obj);
                        new JFCadCliente(obj, objF, 1).setVisible(true);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao editar: " + e.getMessage());
            }
            dispose();
        }
    }//GEN-LAST:event_jmEditarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbCadJogo;
    private javax.swing.JButton jbCadUsuario;
    private javax.swing.JButton jbLocacao;
    private javax.swing.JButton jbRegistro;
    private javax.swing.JButton jbRenovar;
    private javax.swing.JButton jbVenda;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JLabel jlFFxv;
    private javax.swing.JLabel jlInfo;
    private javax.swing.JLabel jlTime;
    private javax.swing.JMenuItem jmAlterarSenha;
    private javax.swing.JMenuItem jmEditarDados;
    private javax.swing.JMenuItem jmJogo;
    private javax.swing.JMenuItem jmUsuario;
    // End of variables declaration//GEN-END:variables
    private void setIcon() {
        ImageIcon imagemTituloJanela = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\ProjetoGames\\src\\br\\com\\ProjetoGames\\imagens\\Icones\\video-game-controller-icon.png");
        setIconImage(imagemTituloJanela.getImage());
    }

    private void tempo() {
        Thread clock = new Thread() {
            public void run() {
                String smonth, sday, ssecond, sminute, shour;
                for (;;) {
                    Calendar cal = new GregorianCalendar();
                    int year = cal.get(Calendar.YEAR);
                    int month = cal.get(Calendar.MONTH) + 1;
                    int day = cal.get(Calendar.DAY_OF_MONTH);
                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR_OF_DAY);
                    if (day < 10) {
                        sday = "0" + day;
                    } else {
                        sday = "" + day;
                    }
                    if (month < 10) {
                        smonth = "0" + month;
                    } else {
                        smonth = "" + month;
                    }
                    if (hour < 10) {
                        shour = "0" + hour;
                    } else {
                        shour = "" + hour;
                    }
                    if (minute < 10) {
                        sminute = "0" + minute;
                    } else {
                        sminute = "" + minute;
                    }
                    if (second < 10) {
                        ssecond = "0" + second;
                    } else {
                        ssecond = "" + second;
                    }
                    jlTime.setText("Data: " + sday + "/" + smonth + "/" + year + " " + shour + ":" + sminute + ":" + ssecond);
                    try {
                        sleep(1000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(JFPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
            }
        };
        clock.start();
    }

    public void windowsClosing() {
        ImageIcon imagemTituloJanela = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\ProjetoGames\\src\\br\\com\\ProjetoGames\\imagens\\524d20cabd4731dffd6453fb707ab1d2b2b11c52_00.gif");
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent we) {
                if (JOptionPane.showConfirmDialog(null, "Deseja \nRealmente \nSair?", "Botão Sair", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, imagemTituloJanela) == JOptionPane.YES_OPTION) {
                    dispose();
                    new JFLogin().setVisible(true);
                }
            }
        });
    }
}
