/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ProjetoGames.view.Operacao;

import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Pedro
 */
public class JIFCarrinhoVenda extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFCarrinhoVenda
     */
    public JIFCarrinhoVenda() {
        initComponents();
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        mudarIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspCarrinho = new javax.swing.JScrollPane();
        jtbCarrinho = new javax.swing.JTable();
        jlSubTotal = new javax.swing.JLabel();
        jlSifraSubTotal = new javax.swing.JLabel();
        jtSubTotal = new javax.swing.JTextField();
        jlTotal = new javax.swing.JLabel();
        jlSifraTotal = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();
        jlCupom = new javax.swing.JLabel();
        jtCupom = new javax.swing.JTextField();
        jlDesconto = new javax.swing.JLabel();
        jtDesconto = new javax.swing.JTextField();
        jlPorcentagem = new javax.swing.JLabel();
        jlMenos = new javax.swing.JLabel();
        jbFinalizarCompra = new javax.swing.JButton();

        setTitle("Carrinho de Compras");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jtbCarrinho.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtbCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Plataforma", "Quantidade", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspCarrinho.setViewportView(jtbCarrinho);

        jlSubTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlSubTotal.setText("SubTotal:");

        jlSifraSubTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlSifraSubTotal.setText("R$");

        jtSubTotal.setEditable(false);
        jtSubTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtSubTotal.setEnabled(false);

        jlTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlTotal.setText("Total:");

        jlSifraTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlSifraTotal.setText("R$");

        jtTotal.setEditable(false);
        jtTotal.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtTotal.setEnabled(false);

        jlCupom.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlCupom.setText("Cupom:");

        jtCupom.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        jlDesconto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlDesconto.setText("Desconto:");

        jtDesconto.setEditable(false);
        jtDesconto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jtDesconto.setEnabled(false);

        jlPorcentagem.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlPorcentagem.setText("%");
        jlPorcentagem.setToolTipText("");

        jlMenos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlMenos.setText("-");

        jbFinalizarCompra.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jbFinalizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Icones/icons8_Checkout_48px.png"))); // NOI18N
        jbFinalizarCompra.setText("Finalizar Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jspCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbFinalizarCompra, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlCupom, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlSifraTotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jlTotal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jlSifraSubTotal)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jlSubTotal, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jlDesconto)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlMenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlPorcentagem)))
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlSubTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSifraSubTotal)
                            .addComponent(jtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jlCupom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCupom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlDesconto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlPorcentagem)
                            .addComponent(jlMenos))
                        .addGap(36, 36, 36)
                        .addComponent(jlTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlSifraTotal)
                            .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jbFinalizarCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jspCarrinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        sair();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbFinalizarCompra;
    private javax.swing.JLabel jlCupom;
    private javax.swing.JLabel jlDesconto;
    private javax.swing.JLabel jlMenos;
    private javax.swing.JLabel jlPorcentagem;
    private javax.swing.JLabel jlSifraSubTotal;
    private javax.swing.JLabel jlSifraTotal;
    private javax.swing.JLabel jlSubTotal;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JScrollPane jspCarrinho;
    private javax.swing.JTextField jtCupom;
    private javax.swing.JTextField jtDesconto;
    private javax.swing.JTextField jtSubTotal;
    private javax.swing.JTextField jtTotal;
    private javax.swing.JTable jtbCarrinho;
    // End of variables declaration//GEN-END:variables
    public void mudarIcon() {
        ImageIcon icon = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\_Projetos\\ProjetoGames\\ProjetoGames2\\src\\br\\com\\ProjetoGames\\imagens\\Icones\\icons8_Shopping_Cart_528px_1.png");
        this.setFrameIcon(icon);
    }

    public void sair() {
        try {
            ImageIcon imagemTituloJanela = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\ProjetoGames\\src\\br\\com\\ProjetoGames\\imagens\\524d20cabd4731dffd6453fb707ab1d2b2b11c52_00.gif");
            if (JOptionPane.showConfirmDialog(null, "Deseja \nRealmente \nVoltar?", "Botão Voltar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, imagemTituloJanela) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
}