/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ProjetoGames.view.Operacao;

import br.com.ProjetoGames.model.JogosModel;
import java.awt.Font;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Pedro
 */
public class JIFDetalhesJogos extends javax.swing.JInternalFrame {

    JogosModel obj = new JogosModel();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    public JIFDetalhesJogos() {
        initComponents();
        obj = new JogosModel();
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        mudarIcon();
    }

    public JIFDetalhesJogos(JogosModel obj) {
        initComponents();
        this.obj = obj;
        preencherCampos();
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        mudarIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlVoltar = new javax.swing.JLabel();
        jlPublisher = new javax.swing.JLabel();
        jlIdJogos = new javax.swing.JLabel();
        jlSituacao = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlPlataforma = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jlDataLancamento = new javax.swing.JLabel();
        jlGenero = new javax.swing.JLabel();
        jlFaixaEtaria = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jtIdJogos = new javax.swing.JTextField();
        jtTitulo = new javax.swing.JTextField();
        jtPublisher = new javax.swing.JTextField();
        jtSituacao = new javax.swing.JTextField();
        jtPlataforma = new javax.swing.JTextField();
        jtDataLancamento = new javax.swing.JTextField();
        jtEstado = new javax.swing.JTextField();
        jtGenero = new javax.swing.JTextField();
        jtFaixaEtaria = new javax.swing.JTextField();
        jtDescricao = new javax.swing.JTextField();
        jlImagemCapa = new javax.swing.JLabel();
        jlQuantidadeVenda = new javax.swing.JLabel();
        jtQuantidadeVenda = new javax.swing.JTextField();
        jlQuantidadeAluga = new javax.swing.JLabel();
        jtQuantidadeAluga = new javax.swing.JTextField();
        jlPrecoVenda = new javax.swing.JLabel();
        jtPrecoVenda = new javax.swing.JTextField();
        jlPrecoAlugar = new javax.swing.JLabel();
        jtPrecoAlugar = new javax.swing.JTextField();
        jlSifraVenda = new javax.swing.JLabel();
        jlSifraAluga = new javax.swing.JLabel();
        jtBackAlugar = new javax.swing.JTextField();
        jtBackVender = new javax.swing.JTextField();
        jlPokedex = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Detalhes do Jogo");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 0, 210, 50));

        jlPublisher.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlPublisher.setText("Publicadora:");
        getContentPane().add(jlPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 110, -1));

        jlIdJogos.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlIdJogos.setText("ID:");
        getContentPane().add(jlIdJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jlSituacao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlSituacao.setText("Situacao:");
        getContentPane().add(jlSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 107, -1));

        jlTitulo.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlTitulo.setText("Título");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 67, -1));

        jlPlataforma.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlPlataforma.setText("Plataforma:");
        getContentPane().add(jlPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 110, -1));

        jlEstado.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlEstado.setText("Estado:");
        getContentPane().add(jlEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 86, -1));

        jlDataLancamento.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlDataLancamento.setText("<html>Data de<br />Lancamento:</html>");
        getContentPane().add(jlDataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jlGenero.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlGenero.setText("Gênero:");
        getContentPane().add(jlGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 80, -1));

        jlFaixaEtaria.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlFaixaEtaria.setText("Faixa Etária:");
        getContentPane().add(jlFaixaEtaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 110, -1));

        jlDescricao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlDescricao.setText("Descricao:");
        getContentPane().add(jlDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 94, -1));

        jtIdJogos.setEditable(false);
        jtIdJogos.setBackground(new java.awt.Color(232, 48, 48));
        jtIdJogos.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtIdJogos.setToolTipText("");
        jtIdJogos.setBorder(null);
        jtIdJogos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtIdJogos.setEnabled(false);
        getContentPane().add(jtIdJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 25, -1));

        jtTitulo.setEditable(false);
        jtTitulo.setBackground(new java.awt.Color(232, 48, 48));
        jtTitulo.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtTitulo.setToolTipText("");
        jtTitulo.setBorder(null);
        jtTitulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtTitulo.setEnabled(false);
        getContentPane().add(jtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 210, -1));

        jtPublisher.setEditable(false);
        jtPublisher.setBackground(new java.awt.Color(248, 248, 248));
        jtPublisher.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtPublisher.setToolTipText("");
        jtPublisher.setBorder(null);
        jtPublisher.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtPublisher.setEnabled(false);
        getContentPane().add(jtPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 190, -1));

        jtSituacao.setEditable(false);
        jtSituacao.setBackground(new java.awt.Color(248, 248, 248));
        jtSituacao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtSituacao.setToolTipText("");
        jtSituacao.setBorder(null);
        jtSituacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtSituacao.setEnabled(false);
        getContentPane().add(jtSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 250, -1));

        jtPlataforma.setEditable(false);
        jtPlataforma.setBackground(new java.awt.Color(248, 152, 216));
        jtPlataforma.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtPlataforma.setToolTipText("");
        jtPlataforma.setBorder(null);
        jtPlataforma.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtPlataforma.setEnabled(false);
        getContentPane().add(jtPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, 170, -1));

        jtDataLancamento.setEditable(false);
        jtDataLancamento.setBackground(new java.awt.Color(168, 112, 248));
        jtDataLancamento.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtDataLancamento.setToolTipText("");
        jtDataLancamento.setBorder(null);
        jtDataLancamento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtDataLancamento.setEnabled(false);
        getContentPane().add(jtDataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 150, 30));

        jtEstado.setEditable(false);
        jtEstado.setBackground(new java.awt.Color(248, 248, 248));
        jtEstado.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtEstado.setToolTipText("");
        jtEstado.setBorder(null);
        jtEstado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtEstado.setEnabled(false);
        getContentPane().add(jtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 320, 250, -1));

        jtGenero.setEditable(false);
        jtGenero.setBackground(new java.awt.Color(248, 248, 248));
        jtGenero.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtGenero.setToolTipText("");
        jtGenero.setBorder(null);
        jtGenero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtGenero.setEnabled(false);
        getContentPane().add(jtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 180, -1));

        jtFaixaEtaria.setEditable(false);
        jtFaixaEtaria.setBackground(new java.awt.Color(248, 248, 248));
        jtFaixaEtaria.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtFaixaEtaria.setToolTipText("");
        jtFaixaEtaria.setBorder(null);
        jtFaixaEtaria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtFaixaEtaria.setEnabled(false);
        getContentPane().add(jtFaixaEtaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 140, -1));

        jtDescricao.setEditable(false);
        jtDescricao.setBackground(new java.awt.Color(248, 248, 248));
        jtDescricao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtDescricao.setToolTipText("");
        jtDescricao.setBorder(null);
        jtDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtDescricao.setEnabled(false);
        getContentPane().add(jtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 730, 100));
        getContentPane().add(jlImagemCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 260, 310));

        jlQuantidadeVenda.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlQuantidadeVenda.setText("<html>Quantidade<br />Venda:</html>");
        getContentPane().add(jlQuantidadeVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, 110, -1));

        jtQuantidadeVenda.setEditable(false);
        jtQuantidadeVenda.setBackground(new java.awt.Color(248, 248, 248));
        jtQuantidadeVenda.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtQuantidadeVenda.setToolTipText("");
        jtQuantidadeVenda.setBorder(null);
        jtQuantidadeVenda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtQuantidadeVenda.setEnabled(false);
        getContentPane().add(jtQuantidadeVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 50, -1));

        jlQuantidadeAluga.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlQuantidadeAluga.setText("<html>Quantidade<br />Alugar:</html>");
        getContentPane().add(jlQuantidadeAluga, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, 100, -1));

        jtQuantidadeAluga.setEditable(false);
        jtQuantidadeAluga.setBackground(new java.awt.Color(248, 248, 248));
        jtQuantidadeAluga.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtQuantidadeAluga.setToolTipText("");
        jtQuantidadeAluga.setBorder(null);
        jtQuantidadeAluga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtQuantidadeAluga.setEnabled(false);
        getContentPane().add(jtQuantidadeAluga, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 70, -1));

        jlPrecoVenda.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlPrecoVenda.setText("<html>Preco<br />Venda:</html>");
        getContentPane().add(jlPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 510, 60, -1));

        jtPrecoVenda.setEditable(false);
        jtPrecoVenda.setBackground(new java.awt.Color(248, 248, 248));
        jtPrecoVenda.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtPrecoVenda.setToolTipText("");
        jtPrecoVenda.setBorder(null);
        jtPrecoVenda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtPrecoVenda.setEnabled(false);
        getContentPane().add(jtPrecoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 560, 80, -1));

        jlPrecoAlugar.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlPrecoAlugar.setText("<html>Preco<br />Alugar:</html>");
        getContentPane().add(jlPrecoAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 100, -1));

        jtPrecoAlugar.setEditable(false);
        jtPrecoAlugar.setBackground(new java.awt.Color(248, 248, 248));
        jtPrecoAlugar.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtPrecoAlugar.setToolTipText("");
        jtPrecoAlugar.setBorder(null);
        jtPrecoAlugar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtPrecoAlugar.setEnabled(false);
        getContentPane().add(jtPrecoAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 560, 90, -1));

        jlSifraVenda.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlSifraVenda.setText("R$");
        getContentPane().add(jlSifraVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, -1, -1));

        jlSifraAluga.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlSifraAluga.setText("R$");
        getContentPane().add(jlSifraAluga, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, -1, -1));

        jtBackAlugar.setEditable(false);
        jtBackAlugar.setAutoscrolls(false);
        jtBackAlugar.setEnabled(false);
        jtBackAlugar.setFocusable(false);
        jtBackAlugar.setOpaque(false);
        jtBackAlugar.setRequestFocusEnabled(false);
        jtBackAlugar.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtBackAlugar.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jtBackAlugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 290, 80));

        jtBackVender.setEditable(false);
        jtBackVender.setAutoscrolls(false);
        jtBackVender.setEnabled(false);
        jtBackVender.setFocusable(false);
        jtBackVender.setOpaque(false);
        jtBackVender.setRequestFocusEnabled(false);
        jtBackVender.setSelectionColor(new java.awt.Color(255, 255, 255));
        jtBackVender.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jtBackVender, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 510, 280, 80));

        jlPokedex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Pokedex Entry empty.png"))); // NOI18N
        getContentPane().add(jlPokedex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        sair();
    }//GEN-LAST:event_jlVoltarMouseClicked

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        sair();
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlDataLancamento;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlFaixaEtaria;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlIdJogos;
    private javax.swing.JLabel jlImagemCapa;
    private javax.swing.JLabel jlPlataforma;
    private javax.swing.JLabel jlPokedex;
    private javax.swing.JLabel jlPrecoAlugar;
    private javax.swing.JLabel jlPrecoVenda;
    private javax.swing.JLabel jlPublisher;
    private javax.swing.JLabel jlQuantidadeAluga;
    private javax.swing.JLabel jlQuantidadeVenda;
    private javax.swing.JLabel jlSifraAluga;
    private javax.swing.JLabel jlSifraVenda;
    private javax.swing.JLabel jlSituacao;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JTextField jtBackAlugar;
    private javax.swing.JTextField jtBackVender;
    private javax.swing.JTextField jtDataLancamento;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtFaixaEtaria;
    private javax.swing.JTextField jtGenero;
    private javax.swing.JTextField jtIdJogos;
    private javax.swing.JTextField jtPlataforma;
    private javax.swing.JTextField jtPrecoAlugar;
    private javax.swing.JTextField jtPrecoVenda;
    private javax.swing.JTextField jtPublisher;
    private javax.swing.JTextField jtQuantidadeAluga;
    private javax.swing.JTextField jtQuantidadeVenda;
    private javax.swing.JTextField jtSituacao;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables

    public void mudarIcon() {
        ImageIcon icon = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\_Projetos\\ProjetoGames\\ProjetoGames2\\src\\br\\com\\ProjetoGames\\imagens\\Icones\\icons8_Pokedex_528px.png");
        this.setFrameIcon(icon);
    }

    public void sair() {
        try {
            ImageIcon imagemTituloJanela = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\ProjetoGames\\src\\br\\com\\ProjetoGames\\imagens\\524d20cabd4731dffd6453fb707ab1d2b2b11c52_00.gif");
            if (JOptionPane.showConfirmDialog(null, "Deseja \nRealmente \nVoltar?", "Botão Voltar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, imagemTituloJanela) == JOptionPane.YES_OPTION) {
                obj = new JogosModel();
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void changeToENG() {
        obj.setTitulo(obj.getTitulo().replace("ç", "c"));
        obj.setTitulo(obj.getTitulo().replace("ã", "a"));
        obj.setTitulo(obj.getTitulo().replace("õ", "o"));
        obj.setTitulo(obj.getTitulo().trim());
        obj.setGenero(obj.getGenero().replace("ç", "c"));
        obj.setGenero(obj.getGenero().replace("ã", "a"));
        obj.setGenero(obj.getGenero().replace("õ", "o"));
        obj.setGenero(obj.getGenero().trim());
        obj.setSituacao(obj.getSituacao().replace("ç", "c"));
        obj.setSituacao(obj.getSituacao().replace("ã", "a"));
        obj.setSituacao(obj.getSituacao().replace("õ", "o"));
        obj.setSituacao(obj.getSituacao().trim());
        obj.setPublisher(obj.getPublisher().replace("ç", "c"));
        obj.setPublisher(obj.getPublisher().replace("ã", "a"));
        obj.setPublisher(obj.getPublisher().replace("õ", "o"));
        obj.setPublisher(obj.getPublisher().trim());
        obj.setDescricao(obj.getDescricao().replace("ç", "c"));
        obj.setDescricao(obj.getDescricao().replace("ã", "a"));
        obj.setDescricao(obj.getDescricao().replace("õ", "o"));
        obj.setDescricao(obj.getDescricao().trim());
        obj.setEstado(obj.getEstado().replace("ç", "c"));
        obj.setEstado(obj.getEstado().replace("ã", "a"));
        obj.setEstado(obj.getEstado().replace("õ", "o"));
        obj.setEstado(obj.getEstado().trim());
        obj.setPlataforma(obj.getPlataforma().replace("ç", "c"));
        obj.setPlataforma(obj.getPlataforma().replace("ã", "a"));
        obj.setPlataforma(obj.getPlataforma().replace("õ", "o"));
        obj.setPlataforma(obj.getPlataforma().trim());
        obj.setPublisher(obj.getPublisher().replace("ç", "c"));
        obj.setPublisher(obj.getPublisher().replace("ã", "a"));
        obj.setPublisher(obj.getPublisher().replace("õ", "o"));
        obj.setPublisher(obj.getPublisher().trim());
    }

    public void preencherCampos() {
        changeToENG();
        jtIdJogos.setText("" + obj.getIdJogos());
        jtTitulo.setText(obj.getTitulo());
        jtPublisher.setText(obj.getPublisher());
        jtGenero.setText(obj.getGenero());
        jtDataLancamento.setText(dateFormat.format(obj.getDataLancamento().getTime()));
        jtSituacao.setText(obj.getSituacao());
        jtEstado.setText(obj.getEstado());
        jtPlataforma.setText(obj.getPlataforma());
        jtDescricao.setText(obj.getDescricao());
        jtFaixaEtaria.setText(obj.getFaixaEtaria());
        jtPrecoAlugar.setText(""+obj.getQuantidadeDisponivel().getValorAlugar());
        jtPrecoVenda.setText(""+obj.getQuantidadeDisponivel().getValorVender());
        jtQuantidadeVenda.setText(""+obj.getQuantidadeDisponivel().getQuantidadeVender());
        jtQuantidadeAluga.setText(""+obj.getQuantidadeDisponivel().getQuantidadeAlugar());
        BufferedImage imagem = byteArrayToImage(obj.getImagem());
        ImageIcon capa = new ImageIcon(imagem);
        
        Image image = capa.getImage(); 
        Image newimg = image.getScaledInstance(220, 290, java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
        capa = new ImageIcon(newimg);  
        jlImagemCapa.setIcon(capa);
    }

    public BufferedImage byteArrayToImage(byte[] bytes) {
        BufferedImage bufferedImage = null;
        try {
            InputStream inputStream = new ByteArrayInputStream(bytes);
            bufferedImage = ImageIO.read(inputStream);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        return bufferedImage;
    }

    /**
     * Resizes an image to a absolute width and height (the image may not be
     * proportional)
     *
     * @param inputImagePath Path of the original image
     * @param outputImagePath Path to save the resized image
     * @param scaledWidth absolute width in pixels
     * @param scaledHeight absolute height in pixels
     * @throws IOException
     */
    public static void resize(String inputImagePath,
            String outputImagePath, int scaledWidth, int scaledHeight)
            throws IOException {
        // reads input image
        File inputFile = new File(inputImagePath);
        BufferedImage inputImage = ImageIO.read(inputFile);

        // creates output image
        BufferedImage outputImage = new BufferedImage(scaledWidth,
                scaledHeight, inputImage.getType());

        // scales the input image to the output image
        Graphics2D g2d = outputImage.createGraphics();
        g2d.drawImage(inputImage, 0, 0, scaledWidth, scaledHeight, null);
        g2d.dispose();

        // extracts extension of output file
        String formatName = outputImagePath.substring(outputImagePath
                .lastIndexOf(".") + 1);

        // writes to output file
        ImageIO.write(outputImage, formatName, new File(outputImagePath));
    }

    /**
     * Resizes an image by a percentage of original size (proportional).
     *
     * @param inputImagePath Path of the original image
     * @param outputImagePath Path to save the resized image
     * @param percent a double number specifies percentage of the output image
     * over the input image.
     * @throws IOException
     */
    public static void resize(String inputImagePath,
            String outputImagePath, double percent) throws IOException {
        File inputFile = new File(inputImagePath);
        BufferedImage inputImage = ImageIO.read(inputFile);
        int scaledWidth = (int) (inputImage.getWidth() * percent);
        int scaledHeight = (int) (inputImage.getHeight() * percent);
        resize(inputImagePath, outputImagePath, scaledWidth, scaledHeight);
    }

}
