/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ProjetoGames.view.Operacao;

import br.com.ProjetoGames.model.JogosModel;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Pedro
 */
public class JIFDetalhesJogos extends javax.swing.JInternalFrame {

    JogosModel obj = new JogosModel();
    DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");

    public JIFDetalhesJogos() {
        initComponents();
        obj = new JogosModel();
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        mudarIcon();
    }

    public JIFDetalhesJogos(JogosModel obj) {
        initComponents();
        this.obj = obj;
        preencherCampos();
        this.setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
        Font font = new Font(Font.SANS_SERIF, Font.PLAIN, 30);
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.buttonFont", font);
        mudarIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlVoltar = new javax.swing.JLabel();
        jlPublisher = new javax.swing.JLabel();
        jlIdJogos = new javax.swing.JLabel();
        jlSituacao = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jlPlataforma = new javax.swing.JLabel();
        jlEstado = new javax.swing.JLabel();
        jlDataLancamento = new javax.swing.JLabel();
        jlGenero = new javax.swing.JLabel();
        jlFaixaEtaria = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jtIdJogos = new javax.swing.JTextField();
        jtTitulo = new javax.swing.JTextField();
        jtPublisher = new javax.swing.JTextField();
        jtSituacao = new javax.swing.JTextField();
        jtPlataforma = new javax.swing.JTextField();
        jtDataLancamento = new javax.swing.JTextField();
        jtEstado = new javax.swing.JTextField();
        jtGenero = new javax.swing.JTextField();
        jtFaixaEtaria = new javax.swing.JTextField();
        jtDescricao = new javax.swing.JTextField();
        jlImagemCapa = new javax.swing.JLabel();
        jlPokedex = new javax.swing.JLabel();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(jlVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 200, 50));

        jlPublisher.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlPublisher.setText("Publicadora:");
        getContentPane().add(jlPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 110, -1));

        jlIdJogos.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlIdJogos.setText("ID:");
        getContentPane().add(jlIdJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, -1));

        jlSituacao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlSituacao.setText("Situacao:");
        getContentPane().add(jlSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 107, -1));

        jlTitulo.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlTitulo.setText("Título");
        getContentPane().add(jlTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 67, -1));

        jlPlataforma.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlPlataforma.setText("Plataforma:");
        getContentPane().add(jlPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 190, 110, -1));

        jlEstado.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlEstado.setText("Estado:");
        getContentPane().add(jlEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 86, -1));

        jlDataLancamento.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlDataLancamento.setText("<html>Data de<br />Lancamento:</html>");
        getContentPane().add(jlDataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        jlGenero.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlGenero.setText("Gênero:");
        getContentPane().add(jlGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 67, -1));

        jlFaixaEtaria.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlFaixaEtaria.setText("Faixa Etária:");
        getContentPane().add(jlFaixaEtaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 110, -1));

        jlDescricao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jlDescricao.setText("Descricao:");
        getContentPane().add(jlDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 94, -1));

        jtIdJogos.setEditable(false);
        jtIdJogos.setBackground(new java.awt.Color(232, 48, 48));
        jtIdJogos.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtIdJogos.setToolTipText("");
        jtIdJogos.setBorder(null);
        jtIdJogos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtIdJogos.setEnabled(false);
        getContentPane().add(jtIdJogos, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, 25, -1));

        jtTitulo.setEditable(false);
        jtTitulo.setBackground(new java.awt.Color(232, 48, 48));
        jtTitulo.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtTitulo.setToolTipText("");
        jtTitulo.setBorder(null);
        jtTitulo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtTitulo.setEnabled(false);
        getContentPane().add(jtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 80, 132, -1));

        jtPublisher.setEditable(false);
        jtPublisher.setBackground(new java.awt.Color(248, 248, 248));
        jtPublisher.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtPublisher.setToolTipText("");
        jtPublisher.setBorder(null);
        jtPublisher.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtPublisher.setEnabled(false);
        getContentPane().add(jtPublisher, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 130, 117, -1));

        jtSituacao.setEditable(false);
        jtSituacao.setBackground(new java.awt.Color(248, 248, 248));
        jtSituacao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtSituacao.setToolTipText("");
        jtSituacao.setBorder(null);
        jtSituacao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtSituacao.setEnabled(false);
        getContentPane().add(jtSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 270, 120, -1));

        jtPlataforma.setEditable(false);
        jtPlataforma.setBackground(new java.awt.Color(248, 152, 216));
        jtPlataforma.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtPlataforma.setToolTipText("");
        jtPlataforma.setBorder(null);
        jtPlataforma.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtPlataforma.setEnabled(false);
        getContentPane().add(jtPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 113, -1));

        jtDataLancamento.setEditable(false);
        jtDataLancamento.setBackground(new java.awt.Color(168, 112, 248));
        jtDataLancamento.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtDataLancamento.setToolTipText("");
        jtDataLancamento.setBorder(null);
        jtDataLancamento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtDataLancamento.setEnabled(false);
        getContentPane().add(jtDataLancamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 90, 30));

        jtEstado.setEditable(false);
        jtEstado.setBackground(new java.awt.Color(248, 248, 248));
        jtEstado.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtEstado.setToolTipText("");
        jtEstado.setBorder(null);
        jtEstado.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtEstado.setEnabled(false);
        getContentPane().add(jtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 320, 120, -1));

        jtGenero.setEditable(false);
        jtGenero.setBackground(new java.awt.Color(248, 248, 248));
        jtGenero.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtGenero.setToolTipText("");
        jtGenero.setBorder(null);
        jtGenero.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtGenero.setEnabled(false);
        getContentPane().add(jtGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 163, -1));

        jtFaixaEtaria.setEditable(false);
        jtFaixaEtaria.setBackground(new java.awt.Color(248, 248, 248));
        jtFaixaEtaria.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtFaixaEtaria.setToolTipText("");
        jtFaixaEtaria.setBorder(null);
        jtFaixaEtaria.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtFaixaEtaria.setEnabled(false);
        getContentPane().add(jtFaixaEtaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 560, 194, -1));

        jtDescricao.setEditable(false);
        jtDescricao.setBackground(new java.awt.Color(248, 248, 248));
        jtDescricao.setFont(new java.awt.Font("Nintendo DS BIOS", 1, 24)); // NOI18N
        jtDescricao.setToolTipText("");
        jtDescricao.setBorder(null);
        jtDescricao.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtDescricao.setEnabled(false);
        getContentPane().add(jtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 690, -1));

        jlImagemCapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlImagemCapaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlImagemCapaMouseExited(evt);
            }
        });
        getContentPane().add(jlImagemCapa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 400, 340));

        jlPokedex.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ProjetoGames/imagens/Pokedex Entry empty.png"))); // NOI18N
        getContentPane().add(jlPokedex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlVoltarMouseClicked
        sair();
    }//GEN-LAST:event_jlVoltarMouseClicked

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        sair();
    }//GEN-LAST:event_formInternalFrameClosing

    private void jlImagemCapaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImagemCapaMouseEntered
        jlImagemCapa.setBounds(0, 40, 500, 400);
    }//GEN-LAST:event_jlImagemCapaMouseEntered

    private void jlImagemCapaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlImagemCapaMouseExited
        jlImagemCapa.setBounds(0, 40, 400, 340);
    }//GEN-LAST:event_jlImagemCapaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlDataLancamento;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlFaixaEtaria;
    private javax.swing.JLabel jlGenero;
    private javax.swing.JLabel jlIdJogos;
    private javax.swing.JLabel jlImagemCapa;
    private javax.swing.JLabel jlPlataforma;
    private javax.swing.JLabel jlPokedex;
    private javax.swing.JLabel jlPublisher;
    private javax.swing.JLabel jlSituacao;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlVoltar;
    private javax.swing.JTextField jtDataLancamento;
    private javax.swing.JTextField jtDescricao;
    private javax.swing.JTextField jtEstado;
    private javax.swing.JTextField jtFaixaEtaria;
    private javax.swing.JTextField jtGenero;
    private javax.swing.JTextField jtIdJogos;
    private javax.swing.JTextField jtPlataforma;
    private javax.swing.JTextField jtPublisher;
    private javax.swing.JTextField jtSituacao;
    private javax.swing.JTextField jtTitulo;
    // End of variables declaration//GEN-END:variables

    public void mudarIcon() {
        ImageIcon icon = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\_Projetos\\ProjetoGames\\ProjetoGames2\\src\\br\\com\\ProjetoGames\\imagens\\Icones\\icons8_Pokedex_528px.png");
        this.setFrameIcon(icon);
    }

    public void sair() {
        try {
            ImageIcon imagemTituloJanela = new ImageIcon("C:\\Users\\Pedro\\Documents\\NetBeansProjects\\Luciene\\ProjetoGames\\src\\br\\com\\ProjetoGames\\imagens\\524d20cabd4731dffd6453fb707ab1d2b2b11c52_00.gif");
            if (JOptionPane.showConfirmDialog(null, "Deseja \nRealmente \nVoltar?", "Botão Voltar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, imagemTituloJanela) == JOptionPane.YES_OPTION) {
                obj = new JogosModel();
                dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    public void changeToENG() {
        obj.setTitulo(obj.getTitulo().replace("ç", "c"));
        obj.setTitulo(obj.getTitulo().replace("ã", "a"));
        obj.setTitulo(obj.getTitulo().replace("õ", "o"));
        obj.setTitulo(obj.getTitulo().trim());
        obj.setGenero(obj.getGenero().replace("ç", "c"));
        obj.setGenero(obj.getGenero().replace("ã", "a"));
        obj.setGenero(obj.getGenero().replace("õ", "o"));
        obj.setGenero(obj.getGenero().trim());
        obj.setSituacao(obj.getSituacao().replace("ç", "c"));
        obj.setSituacao(obj.getSituacao().replace("ã", "a"));
        obj.setSituacao(obj.getSituacao().replace("õ", "o"));
        obj.setSituacao(obj.getSituacao().trim());
        obj.setPublisher(obj.getPublisher().replace("ç", "c"));
        obj.setPublisher(obj.getPublisher().replace("ã", "a"));
        obj.setPublisher(obj.getPublisher().replace("õ", "o"));
        obj.setPublisher(obj.getPublisher().trim());
        obj.setDescricao(obj.getDescricao().replace("ç", "c"));
        obj.setDescricao(obj.getDescricao().replace("ã", "a"));
        obj.setDescricao(obj.getDescricao().replace("õ", "o"));
        obj.setDescricao(obj.getDescricao().trim());
        obj.setEstado(obj.getEstado().replace("ç", "c"));
        obj.setEstado(obj.getEstado().replace("ã", "a"));
        obj.setEstado(obj.getEstado().replace("õ", "o"));
        obj.setEstado(obj.getEstado().trim());
        obj.setPlataforma(obj.getPlataforma().replace("ç", "c"));
        obj.setPlataforma(obj.getPlataforma().replace("ã", "a"));
        obj.setPlataforma(obj.getPlataforma().replace("õ", "o"));
        obj.setPlataforma(obj.getPlataforma().trim());
        obj.setPublisher(obj.getPublisher().replace("ç", "c"));
        obj.setPublisher(obj.getPublisher().replace("ã", "a"));
        obj.setPublisher(obj.getPublisher().replace("õ", "o"));
        obj.setPublisher(obj.getPublisher().trim());
    }

    public void preencherCampos() {
        changeToENG();
        jtIdJogos.setText("" + obj.getIdJogos());
        jtTitulo.setText(obj.getTitulo());
        jtPublisher.setText(obj.getPublisher());
        jtGenero.setText(obj.getGenero());
        jtDataLancamento.setText(dateFormat.format(obj.getDataLancamento().getTime()));
        jtSituacao.setText(obj.getSituacao());
        jtEstado.setText(obj.getEstado());
        jtPlataforma.setText(obj.getPlataforma());
        jtDescricao.setText(obj.getDescricao());
        jtFaixaEtaria.setText(obj.getFaixaEtaria());
        BufferedImage imagem = byteArrayToImage(obj.getImagem());
        ImageIcon capa = new ImageIcon(imagem);
        jlImagemCapa.setIcon(capa);
    }

    public BufferedImage byteArrayToImage(byte[] bytes) {
        BufferedImage bufferedImage = null;
        try {
            InputStream inputStream = new ByteArrayInputStream(bytes);
            bufferedImage = ImageIO.read(inputStream);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        return bufferedImage;
    }

//    public void opaMeu() {
//         // read in the original image from an input stream
//        SeekableStream s = SeekableStream.wrapInputStream(
//                inputStream, true);
//        RenderedOp image = JAI.create("stream", s);
//        ((OpImage) image.getRendering()).setTileCache(null);
//
//// now resize the image
//        float scale = newWidth / image.getWidth();
//
//        RenderedOp resizedImage = JAI.create("SubsampleAverage",
//                image, scale, scale, qualityHints);
//
//// lastly, write the newly-resized image to an
//// output stream, in a specific encoding
//        JAI.create("encode", resizedImage, outputStream, "PNG", null);
//    }
}
